const path = require("path")
const fs = require("fs")
const webpack = require('webpack');
// 用于在构建过程中检测文件路径的大小写
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin')
const { WebpackManifestPlugin } = require('webpack-manifest-plugin')
const debug = require('debug')('kiwi-scripts:config:webpack')
// Webpack 构建完成后执行的任务
const PostCompile = require('post-compile-webpack-plugin')

const rootDir = path.join(__dirname, 'client')

const fromRoot = (...p) => path.join(rootDir, ...p)
const hasFile = (...p) => fs.existsSync(fromRoot(...p))

const firstFile = (...files) => {
  const file = files.find((f) => hasFile(f))
  if (file) {
    return fromRoot(file)
  } else {
    return null
  }
}

const configFn = () => {

  const postcssLoader = {
    loader: require.resolve('postcss-loader'),
    options: {
      sourceMap: true,
      postcssOptions: {
        ident: 'postcss',
        config: false,
        plugins:[
          require('postcss-flexbugs-fixes'),
          require('autoprefixer')({
            overrideBrowserslist: [
              '>1%',
              'last 4 versions',
              'Firefox ESR',
              'not ie < 9',
            ],
            flexbox: 'no-2009',
          }),
        ]
      },
    },
  }
  const getCssLoader = (options) => ({
    loader: require.resolve('css-loader'),
    options: {
      modules: {
        localsConvention: 'camelCase',
      },
      importLoaders: 1,
      sourceMap: true,
      ...options,
    },
  })
  const styleLoader = {
    loader: require.resolve('style-loader'),
  }
  const publicPath = 'http://localhost:7975/client/'
  
  const config = {
    context: fromRoot('src'),
    entry: firstFile('./src/index.tsx', './src/index.ts', './src/index.js'),
    output: {
      path: fromRoot('dist'),
      pathinfo: true,
      filename: 'bundle.js',
      publicPath,
    },
    mode: 'development',
    resolve: {
      modules: [fromRoot('src'), 'shared', 'node_modules'],
      extensions: ['.tsx', '.ts', '.js', '.json'],
      fallback: {
        dgram: false,
        fs: false,
        net: false,
        tls: false,
        child_process: false,
      },
    },
    devtool: 'cheap-module-source-map',
    optimization: {
      moduleIds: 'named',
      minimize: false,
      emitOnErrors: false,
      concatenateModules: false,
    },
    module: {
      rules: [
        {
          oneOf: [
            {
              test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
              loader: require.resolve('url-loader'),
              options: {
                limit: 100000,
                name: 'assets/[name].[ext]'
              },
            },
            {
              test: /\.(js|tsx|ts)$/,
              include: fromRoot('src'),
              loader: require.resolve('babel-loader'),
              options: {
                cacheDirectory: true
              },
            },
            {
              test: /\.module\.css$/,
              use: [
                styleLoader,
                getCssLoader({ modules: true }),
                postcssLoader,
              ],
            },
            {
              test: /\.css$/,
              exclude: /\.module\.css$/,
              use: [
                styleLoader,
                getCssLoader({ modules: false }),
                postcssLoader,
              ],
            },
            {
              test: /\.scss$/,
              use: [
                styleLoader,
                getCssLoader({ modules: false }),
                {
                  loader: 'sass-loader',
                  options: {
                    sourceMap: true,
                  },
                },
              ],
            },
            {
              exclude: [
                /\.(js|ts|tsx)$/,
                /\.html$/,
                /\.json$/,
                /\.ejs$/,
                /\.mjs$/,
              ],
              loader: require.resolve('file-loader'),
              options: {
                name: 'assets/[name].[ext]',
              },
            },
          ],
        },
      ],
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.env.CLIENT_PORT': JSON.stringify(process.env.CLIENT_PORT),
        'process.env.PORT': JSON.stringify(process.env.PORT),
      }),
      new webpack.IgnorePlugin({
        resourceRegExp: /^\.\/locale$/,
        contextRegExp: /moment$/,
      }),
      new CaseSensitivePathsPlugin(),
      new WebpackManifestPlugin({
        fileName: 'asset-manifest.json',
        writeToFileEmit: true,
        seed: {
          info: 'this file is generated by the webpack build from kiwi-scripts. Do not modify directly.',
          assets: {},
        },
        generate(seed, files) {
          return files.reduce((manifest, asset) => {
            const {
              chunk: ignoredChunk,
              ...assetProps
            } = asset
            manifest.assets[asset.name] = {
              ...assetProps,
              path: assetProps.path.replace(/^\/client\//, ''),
              fullPath: assetProps.path,
            }
            return manifest
          }, seed)
        },
      }),
      //在打包构建中输出当前的进度和简述
      new webpack.ProgressPlugin(),
      new PostCompile(() => {
        console.log('Your app is running at http://localhost:3000')
      })
    ],
    performance: {
      hints: false,
      maxEntrypointSize: 1000000,
      maxAssetSize: 1000000,
    },
    bail: false,
    devServer: {
      client: {
        overlay: false,
        logging: 'info',
      },
      devMiddleware: {
        publicPath,
      },
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': '*',
        'Access-Control-Allow-Headers': '*',
        'Cross-Origin-Resource-Policy': 'cross-origin'
      },
      static: {
        directory: fromRoot('dist'),
      },
      historyApiFallback: true,
      host: 'localhost',
      hot: true,
      allowedHosts: [
        'localhost',
        'localhost.mango.com',
        'localhost.qa.mango.com',
        '.mango.com',
        '.kiwiinc.com',
      ],
      port: process.env.CLIENT_PORT || 7975,
    },
  }
  debug(config)
  console.log('*********************src***********************')
  return config
}


module.exports = configFn()


